CREATE TABLE rol (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100),
    descripcion VARCHAR(255)
);

CREATE TABLE estado_contrato (
    id_estado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50)
);

CREATE TABLE plantilla (
    id_plantilla INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150),
    tipo_contrato VARCHAR(50),
    descripcion_uso VARCHAR(255),
    cuerpo TEXT,
    estado VARCHAR(30),
    version INTEGER
);

CREATE TABLE usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol INTEGER REFERENCES rol(id_rol),
    nombre VARCHAR(100),
    apellido VARCHAR(100),
    email VARCHAR(150),
    contrasenia_hash VARCHAR(255),
    estado VARCHAR(30),
    intentos_fallidos INTEGER
);

CREATE TABLE campo_plantilla (
    id_campo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_plantilla INTEGER REFERENCES plantilla(id_plantilla),
    marcador VARCHAR(100),
    tipo_dato VARCHAR(50)
);

CREATE TABLE contrato (
    id_contrato INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estado INTEGER REFERENCES estado_contrato(id_estado),
    id_plantilla INTEGER REFERENCES plantilla(id_plantilla),
    id_usuario_creador INTEGER REFERENCES usuario(id_usuario),
    nombre VARCHAR(150),
    descripcion_propiedad VARCHAR(255),
    fecha_inicio DATE,
    fecha_expiracion DATE
);

CREATE TABLE transicion_estado (
    id_transicion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estado_origen INTEGER REFERENCES estado_contrato(id_estado),
    id_estado_destino INTEGER REFERENCES estado_contrato(id_estado)
);

CREATE TABLE version_contrato (
    id_version INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_contrato INTEGER REFERENCES contrato(id_contrato),
    id_usuario_autor INTEGER REFERENCES usuario(id_usuario),
    numero_version INTEGER,
    contenido TEXT,
    fecha_creacion TIMESTAMP,
    hash_sha256 VARCHAR(64)
);

CREATE TABLE usuario_contrato (
    id_parte INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_contrato INTEGER REFERENCES contrato(id_contrato),
    id_usuario INTEGER REFERENCES usuario(id_usuario),
    correo_invitado VARCHAR(150),
    rol_parte VARCHAR(50),
    estado_invitacion VARCHAR(30),
    fecha_invitacion TIMESTAMP,
    token_invitacion VARCHAR(255)
);

CREATE TABLE comentario (
    id_comentario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_contrato INTEGER REFERENCES contrato(id_contrato),
    id_usuario INTEGER REFERENCES usuario(id_usuario),
    texto TEXT,
    fecha_publicacion TIMESTAMP
);

CREATE TABLE firma (
    id_firma INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_parte INTEGER REFERENCES usuario_contrato(id_parte),
    id_version INTEGER REFERENCES version_contrato(id_version),
    estado_firma VARCHAR(30),
    fecha_firma TIMESTAMP,
    hash_firma VARCHAR(255)
);

CREATE TABLE documento_pdf (
    id_pdf INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_version INTEGER REFERENCES version_contrato(id_version),
    nombre_archivo VARCHAR(255),
    contenido_final BYTEA,
    fecha_generacion TIMESTAMP,
    hash_documento VARCHAR(64)
);

CREATE TABLE notificacion (
    id_notificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER REFERENCES usuario(id_usuario),
    id_contrato INTEGER REFERENCES contrato(id_contrato),
    tipo VARCHAR(50),
    canal VARCHAR(50),
    correo_destino VARCHAR(150),
    mensaje TEXT,
    estado_envio VARCHAR(30),
    fecha_envio TIMESTAMP
);

CREATE TABLE preferencia_notificacion (
    id_preferencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER REFERENCES usuario(id_usuario),
    canal VARCHAR(50),
    activa BOOLEAN
);

CREATE TABLE sesion (
    id_sesion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER REFERENCES usuario(id_usuario),
    token VARCHAR(255),
    datos_sesion TEXT,
    estado VARCHAR(30),
    fecha_inicio TIMESTAMP,
    fecha_expiracion TIMESTAMP
);

CREATE TABLE token_seguridad (
    id_token INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER REFERENCES usuario(id_usuario),
    tipo_token VARCHAR(20),
    valor VARCHAR(255),
    usado BOOLEAN,
    fecha_creacion TIMESTAMP,
    fecha_expiracion TIMESTAMP
);

CREATE TABLE auditoria (
    id_registro INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER REFERENCES usuario(id_usuario),
    tipo_accion VARCHAR(50),
    entidad_afectada VARCHAR(100),
    id_entidad_afectada INTEGER,
    descripcion TEXT,
    direccion_ip VARCHAR(45),
    fecha_hora TIMESTAMP
);


ALTER TABLE contrato ALTER COLUMN nombre TYPE VARCHAR(200);
ALTER TABLE contrato ALTER COLUMN descripcion_propiedad TYPE VARCHAR(2000);
ALTER TABLE contrato ADD COLUMN partes_involucradas VARCHAR(1000);

ALTER TABLE version_contrato ADD COLUMN comentario VARCHAR(500);
ALTER TABLE version_contrato ADD COLUMN razon_restauracion VARCHAR(500);

ALTER TABLE usuario_contrato ALTER COLUMN correo_invitado TYPE VARCHAR(254);
ALTER TABLE usuario_contrato ADD COLUMN nombre_parte VARCHAR(150);
ALTER TABLE usuario_contrato ADD COLUMN fecha_expiracion_token TIMESTAMP;

ALTER TABLE comentario ADD COLUMN texto_seleccionado TEXT;
ALTER TABLE comentario ADD COLUMN id_parte INTEGER REFERENCES usuario_contrato(id_parte);

-- Firma: enlace de firma, IP, intentos OTP, bloqueo, fecha límite, último evento
ALTER TABLE firma ADD COLUMN token_firma VARCHAR(255);
ALTER TABLE firma ADD COLUMN fecha_expiracion_token TIMESTAMP;
ALTER TABLE firma ADD COLUMN direccion_ip VARCHAR(45);
ALTER TABLE firma ADD COLUMN intentos_otp_fallidos INTEGER;
ALTER TABLE firma ADD COLUMN enlace_bloqueado BOOLEAN;
ALTER TABLE firma ADD COLUMN fecha_limite DATE;
ALTER TABLE firma ADD COLUMN fecha_ultimo_evento TIMESTAMP;

-- El OTP de un firmante externo se vincula a la parte
ALTER TABLE token_seguridad ADD COLUMN id_parte INTEGER REFERENCES usuario_contrato(id_parte);

-- Bloqueo temporal de 15 minutos
ALTER TABLE usuario ADD COLUMN bloqueado_hasta TIMESTAMP;

ALTER TABLE usuario ALTER COLUMN email TYPE VARCHAR(254);

ALTER TABLE plantilla ALTER COLUMN nombre TYPE VARCHAR(200);
ALTER TABLE plantilla ALTER COLUMN descripcion_uso TYPE VARCHAR(500);

ALTER TABLE preferencia_notificacion ADD COLUMN tipo_evento VARCHAR(50);

ALTER TABLE auditoria ADD COLUMN datos_antes TEXT;
ALTER TABLE auditoria ADD COLUMN datos_despues TEXT;
ALTER TABLE auditoria ADD COLUMN id_version INTEGER REFERENCES version_contrato(id_version);

ALTER TABLE notificacion ALTER COLUMN correo_destino TYPE VARCHAR(254);


INSERT INTO rol (nombre, descripcion) VALUES
    ('Administrador', 'Administrador del sistema'),
    ('Abogado', 'Abogado'),
    ('Agente Inmobiliario', 'Agente Inmobiliario');

INSERT INTO estado_contrato (nombre) VALUES
    ('Borrador'),
    ('En Revisión'),
    ('Listo para firmar'),
    ('Firmado'),
    ('Archivado');

INSERT INTO transicion_estado (id_estado_origen, id_estado_destino)
SELECT o.id_estado, d.id_estado
FROM estado_contrato o, estado_contrato d
WHERE (o.nombre = 'Borrador' AND d.nombre = 'En Revisión')
   OR (o.nombre = 'En Revisión' AND d.nombre = 'Listo para firmar')
   OR (o.nombre = 'Firmado' AND d.nombre = 'Archivado');
