spring.application.name=core

spring.datasource.url=${DB_URL:jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${DB_USERNAME:postgres.noyfyglfygvhtiurfese}
spring.datasource.password=${DB_PASSWORD:Dapp038288**}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.mail.host=${MAIL_HOST:}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
firmaya.mail.remitente=${MAIL_FROM:${MAIL_USERNAME:}}

firmaya.frontend-url=${FRONTEND_URL:http://localhost:3000}
